//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Tellurian.Trains.WiFreds.Resources;

using System.Globalization;
using System.Resources;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
internal static partial class Messages
{
    private static ResourceManager? resourceMan;

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    internal static ResourceManager ResourceManager
    {
        get
        {
            if (resourceMan is null)
            {
                var temp = new ResourceManager("Tellurian.Trains.WiFreds.Resources.Messages", typeof(Messages).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    internal static CultureInfo? Culture { get; set; }

    /// <summary>
    ///   Looks up a localized string similar to wiFRED Server.
    /// </summary>
    internal static string AppTitle => ResourceManager.GetString("AppTitle", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to Connected wiFREDs.
    /// </summary>
    internal static string ConnectedWiFREDs => ResourceManager.GetString("ConnectedWiFREDs", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to No wiFRED devices currently connected..
    /// </summary>
    internal static string NoDevicesConnected => ResourceManager.GetString("NoDevicesConnected", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to Name.
    /// </summary>
    internal static string Name => ResourceManager.GetString("Name", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to IP Address.
    /// </summary>
    internal static string IPAddress => ResourceManager.GetString("IPAddress", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to Loco Addresses.
    /// </summary>
    internal static string LocoAddresses => ResourceManager.GetString("LocoAddresses", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to Last Seen.
    /// </summary>
    internal static string LastSeen => ResourceManager.GetString("LastSeen", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to (unnamed).
    /// </summary>
    internal static string Unnamed => ResourceManager.GetString("Unnamed", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to Last updated.
    /// </summary>
    internal static string LastUpdated => ResourceManager.GetString("LastUpdated", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to Loco Address Conflicts.
    /// </summary>
    internal static string LocoAddressConflicts => ResourceManager.GetString("LocoAddressConflicts", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to Loco Address.
    /// </summary>
    internal static string LocoAddress => ResourceManager.GetString("LocoAddress", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to Conflicting Devices.
    /// </summary>
    internal static string ConflictingDevices => ResourceManager.GetString("ConflictingDevices", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to An unhandled error has occurred..
    /// </summary>
    internal static string UnhandledError => ResourceManager.GetString("UnhandledError", Culture)!;

    /// <summary>
    ///   Looks up a localized string similar to Reload.
    /// </summary>
    internal static string Reload => ResourceManager.GetString("Reload", Culture)!;
}
